import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { projectApi } from '../api/projectApi'
import toast from 'react-hot-toast'

export default function ProjectHistory() {
  const [projects, setProjects] = useState([])
  const [query, setQuery] = useState('')
  const [loading, setLoading] = useState(false)

  const loadAll = async () => {
    setLoading(true)
    try {
      const { data } = await projectApi.list(0, 50)
      setProjects(data.content || [])
    } catch (err) {
      toast.error('Failed to load project history')
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => { loadAll() }, [])

  const handleSearch = async (e) => {
    e.preventDefault()
    if (!query.trim()) return loadAll()
    setLoading(true)
    try {
      const { data } = await projectApi.search(query)
      setProjects(data)
    } catch (err) {
      toast.error('Search failed')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="max-w-6xl mx-auto p-8 space-y-8 animate-fade-in">
      
      {/* Title block */}
      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
        <div className="space-y-2">
          <h1 className="text-3xl font-extrabold bg-gradient-to-r from-white via-slate-200 to-slate-400 bg-clip-text text-transparent">
            Your Project Blueprints
          </h1>
          <p className="text-slate-400 text-sm">Browse, search, and manage all codebases generated by your AI agents.</p>
        </div>

        {/* Search form */}
        <form onSubmit={handleSearch} className="flex gap-3 w-full md:max-w-md">
          <div className="relative flex-1">
            <span className="absolute inset-y-0 left-3 flex items-center text-slate-500">
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
              </svg>
            </span>
            <input
              className="w-full bg-[#080d17]/60 border border-slate-850 focus:border-indigo-500/50 rounded-xl pl-9 pr-4 py-2.5 text-xs text-slate-200 focus:outline-none focus:ring-1 focus:ring-indigo-500/50 transition-all duration-200"
              placeholder="Search by title..."
              value={query}
              onChange={(e) => setQuery(e.target.value)}
            />
          </div>
          <button className="btn-primary py-2.5 px-5 text-xs font-bold shrink-0" type="submit">
            Search
          </button>
        </form>
      </div>

      {loading ? (
        <div className="flex flex-col items-center justify-center py-20 space-y-3">
          <div className="h-8 w-8 rounded-full border-2 border-indigo-500 border-t-transparent animate-spin"></div>
          <span className="text-xs text-slate-500">Loading project records...</span>
        </div>
      ) : projects.length === 0 ? (
        <div className="glass-panel p-16 text-center space-y-4">
          <div className="text-slate-500 text-sm">No project records found.</div>
          <Link to="/generate" className="btn-primary inline-flex py-2 px-5 text-xs font-bold">
            Create Your First Project
          </Link>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
          {projects.map((p, idx) => (
            <div 
              key={p.id} 
              className="glass-panel p-6 flex flex-col justify-between hover:border-indigo-500/30 transition-all duration-200 group"
            >
              <div className="space-y-3">
                <div className="flex items-start justify-between gap-3">
                  <h3 className="font-bold text-white text-base group-hover:text-indigo-400 transition-colors duration-150">
                    <Link to={`/projects/${p.id}`}>{p.title}</Link>
                  </h3>
                  <span className="px-2 py-0.5 rounded text-[8px] font-extrabold tracking-wider bg-teal-500/10 text-teal-400 border border-teal-500/20 uppercase shrink-0">
                    {p.status || 'COMPLETED'}
                  </span>
                </div>
                <p className="text-slate-400 text-xs line-clamp-2 leading-relaxed">
                  {p.originalRequirement || 'Generated codebase layout.'}
                </p>
              </div>

              <div className="mt-6 pt-4 border-t border-slate-850/80 flex flex-wrap items-center justify-between gap-4">
                <div className="flex flex-wrap gap-1">
                  {(p.techStack || ['Java', 'Spring Boot']).map((t) => (
                    <span key={t} className="px-2 py-0.5 rounded bg-slate-950 text-[9px] font-bold text-slate-500 border border-slate-850">
                      {t}
                    </span>
                  ))}
                </div>
                
                <div className="flex items-center gap-3">
                  <Link 
                    to={`/projects/${p.id}/chat`} 
                    className="text-[10px] font-bold text-slate-400 hover:text-white transition"
                  >
                    Chat
                  </Link>
                  <Link 
                    to={`/projects/${p.id}`} 
                    className="text-[10px] font-bold text-indigo-400 hover:text-indigo-300 transition"
                  >
                    Open Workspace →
                  </Link>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}
